### ISSUE TITLE
npm install fails on webapp name

### ISSUE THREAD

**Issue by rkofman** [sukima/generator-gulpify-webapp#1]
```
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.34
npm ERR! npm  v2.3.0

npm ERR! Invalid name: "gulpify webapp"
```

Running npm v2.3.0. Changing the name to `gulpify-webapp` seems to fix the problem.

**Comment by sukima** [comment]
@rkofman thanks for the report, I'm a little confused. You said "Changing the name to `gulpify-webapp` seems to fixes the problem."; however, the name of the project is already `gulpify-webapp`. Is there something in the code or README that suggests the name is something else?

Would you be willing to include your shell command you executed to create the error? Thanks.

**Comment by rkofman** [comment]
Closing old issue, and apologies for never following up -- likely my own user error.
